
import closeWhite from './closeWhite.svg'
import lang from './lang.svg'
import logo from './logo.svg'
import bell from './Bell.svg'
import phone from './Phone.svg'
import lockPassword from './LockPassword.svg'
import eyeOn from './EyeOpen.svg'
import eyeOff from './EyeClosed.svg'
import fingerprint from './fingerprint.svg'
import google from './google.svg'
import facebook from './facebook.svg'
import apple from './apple.svg'
import ArrowLeft from './arrowLeft.svg'
import User from './User.svg'
import UserTab from './userTab.svg'
import Building from './Buildings.svg'
import Policies from './policies.svg'
import InsuranceClaims from './insuranceClaims.svg'
import Pricing from './pricing.svg'

import Close from './Close.svg'
import Error from './Error.svg'
import Information from './Information.svg'
import InformationClose from './InformationClose.svg'
import biometricModal from './biometricModal.svg'
import circle from './Circle.svg'
import circleChecked from './CircleChecked.svg'
import SuccessModalIcon from './SuccessModalIcon.svg'
import BackArrow from "./BackArrow.svg"
import OnboardingNextArrow from "./OnboardingNextArrow.svg"
 
export class Components {
    static onBoarding1 = require('./onboarding1.png');
    static onBoarding2 = require('./onboarding2.png');
    static onBoarding3 = require('./onboarding3.png');
    static homeIcon = require('./HomeIcon.png');
    static ourProduct = require('./ourProduct.png');
    static claims = require('./claims.png');
    static menu = require('./menu.png');
    static whatsApp = require('./whatsApp.png');
    static AppHeaderImageBG = require('./AppHeaderImageBG.png');
    static offersDummy = require('./offersDummy.png');
    static vehicleInsurance = require('./vehicleInsurance.png');
    static medicalInsurance = require('./medicalInsurance.png');
    static otherInsurance = require('./otherInsurance.png');
    static engineeringInsurance = require('./engineeringInsurance.png');
    static transitInsurance = require('./transitInsurance.png');
    static otherCompanyInsurance = require('./otherCompanyInsurance.png');
    static closeWhite = closeWhite;
    static lang = lang;
    static logo = logo;
    static phone = phone;
    static lockPassword = lockPassword;
    static eyeOn = eyeOn;
    static eyeOff = eyeOff;
    static fingerprint = fingerprint;
    static google = google;
    static facebook = facebook;
    static apple = apple;
    static ArrowLeft = ArrowLeft;
    static User = User;
    static bell = bell;
    static userTab = UserTab;
    static building = Building;
    static policies = Policies;
    static insuranceClaims = InsuranceClaims;
    static pricing = Pricing;
    static Close = Close;
    static Error = Error;
    static Information = Information;
    static InformationClose = InformationClose;
    static biometricModal = biometricModal;
    static circle = circle;
    static circleChecked = circleChecked;
    static SuccessModalIcon = SuccessModalIcon;
    static BackArrow = BackArrow;
    static OnboardingNextArrow = OnboardingNextArrow;
}